### ISSUE TITLE
BUG: Windows 11 Exception

### ISSUE THREAD

**Issue by Amit-Kakaiya** [Ross-Patterson/Portals-Desktop-Organization#312]
### Check the Help Site and GitHub Issues/Discussions

- [X] I have checked and found nothing.

### Version

3.2.1.0

### Operating System

Windows 11

### What happened?

Version: 3.2.1.0
Event Source: Application.Current.DispatcherUnhandledException
Internet Connected: yes

Exception Source: Portals

Message:
Object reference not set to an instance of an object.

StackTrace:
   at Portals.ViewModels.PortalWindowViewModel.ClosePortal(Boolean promptToClose, Boolean promptDeleteEmptyFolder)
   at Portals.ViewModels.PortalWindowViewModel.ExecuteClosePortalCommand()
   at MS.Internal.Commands.CommandHelpers.CriticalExecuteCommandSource(ICommandSource commandSource, Boolean userInitiated)
   at System.Windows.Controls.Primitives.ButtonBase.OnClick()
   at System.Windows.Controls.Button.OnClick()
   at System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   at System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   at System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   at System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   at System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   at System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   at System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   at System.Windows.Input.InputManager.ProcessStagingArea()
   at System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   at System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   at System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   at System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   at MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   at System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   at System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)

TargetSite:
Void ClosePortal(Boolean, Boolean)

### Steps to Reproduce

Starting Windows 11 Laptop and getting above exception.
![PortalError](https://github.com/Ross-Patterson/Portals-Desktop-Organization/assets/71107438/f8e76abf-68d5-41ff-8213-81f2ae88d9e4)

### What would you expect to happen?

Show Grouping on Desktops files.

**Comment by Ross-Patterson** [comment]
Hi, can you let me know what action was being performed at the time?

I can see the crash seems to be upon closing a portal.

**Comment by Amit-Kakaiya** [comment]
I have put Portal in Startup folder so on each restart in open up automatically.

**Comment by Ross-Patterson** [comment]
Try clearing out the following folder and trying again:
C:\Users\<username>\AppData\Local\Portals

This will give the app a fresh start.

**Comment by Amit-Kakaiya** [comment]
Will give it a go.

**Comment by Ross-Patterson** [comment]
Did you get it working?

**Comment by Amit-Kakaiya** [comment]
Ross, I am not using it. It also asks to install some update.

**Comment by Ross-Patterson** [comment]
You can install the update.

But since you are not using it and this issue is specific to you I will close the issue.
